FROM mcr.microsoft.com/playwright:v1.47.0-focal

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}

# Playwright browsers are already installed in this base image
